### PR TITLE
Added code Saratrial.cpp

### PR DESCRIPTION
**Pull request by saragabri**
Added code to read the file Uppsala.dat and find the highest temperature and the hottest day for each year. It still does not work. At the moment I am stuck on this point.

### CODE REVIEW

**Review by johanbook — CHANGES_REQUESTED** [review]
When declaring the variable table, has ndata been assigned a value?

Some indentation would be nice (i.e. the main function)

Add comment describing the Function_maxT and int Numberoutofdate.

**Comment by johanbook** [comment]
What is it that does not work?

**Comment by saragabri** [comment]
This are the error messages:
Saratrial.cpp:10:44: error: array bound is not an integer constant before
‘]’ token
 double Function_maxT(double tabella[][ndata], int *giorno, double
Tmax_temporan
                                            ^
Saratrial.cpp:10:45: error: expected ‘)’ before ‘,’ token
 double Function_maxT(double tabella[][ndata], int *giorno, double
Tmax_temporan
                                             ^
Saratrial.cpp:10:47: error: expected unqualified-id before ‘int’
 double Function_maxT(double tabella[][ndata], int *giorno, double
Tmax_temporan
                                               ^
Saratrial.cpp:68:42: error: array bound is not an integer constant before
‘]’ token
 double Function_maxT(double table[][ndata], int *giorno, double
Tmax_temporanea
                                          ^
Saratrial.cpp:68:43: error: expected ‘)’ before ‘,’ token
 double Function_maxT(double table[][ndata], int *giorno, double
Tmax_temporanea
                                           ^
Saratrial.cpp:68:45: error: expected unqualified-id before ‘int’
 double Function_maxT(double table[][ndata], int *giorno, double
Tmax_temporanea



2017-11-05 13:53 GMT+01:00 Johan Book <notifications@github.com>:

**Comment by saragabri** [comment]
I modified the code. Now the program should just find the highest temperature of each year. I get no errors in the compilation,but, when executed, the program gives segmentation fault.

**Review by johanbook — APPROVED** [review]

**Comment by johanbook** [comment]
On line 18:
double table [6][106640] should probably be double table [106640][6]

**Comment by saragabri** [comment]
Saratrial.cpp is now working. It reads the data from Uppsala.dat and finds the highest temperature. It also collects the highest temperature of each year in an array.

**Comment by johanbook** [comment]
Good job!

**Pull request merged**
